/**
 * Connection practices the two people coaches were missing.
 *
 * The relationship and family coaches were written for one household: a
 * partner, primary-school kids, a nine-to-five. A carer had nothing for
 * their own recovery, a parent of teenagers got a three-hour Saturday
 * outing and a 5:15pm slot written for a nine-year-old, and a couple with
 * no kids was handed "one-on-one with each child". These entries fill
 * those gaps. Same sourcing policy as the main library (docs/KNOWLEDGE.md),
 * same rule for this pillar: nothing here claims an A, because nothing
 * about couple or family behaviour has that kind of support.
 */

import type { Protocol } from './protocols';

export const PEOPLE_PROTOCOLS: Protocol[] = [
  // ── Connection: the carer's own recovery ─────────────────────────────
  {
    id: 'carer-own-hours',
    evidenceLevel: 'C',
    title: 'Two hours that are yours',
    pillar: 'connection',
    area: 'health',
    goalDomains: ['family', 'health', 'personal'],
    summary: 'Two hours a week, in the calendar, with cover arranged — not spent on chores, not spent catching up, yours.',
    why: 'Reviews of support for family carers keep finding the same thing: a real break, taken, lowers strain and low mood a little, and the people who never get one are the ones who go under. The break only counts if it actually happens, which is why it goes in the week first.',
    attribution: ['Barbara Fiese', 'Tim Ferriss'],
    days: [6],
    durationMin: 120,
    anchor: { kind: 'fixed', start: '10:00', windowMin: 300 },
    energy: 'any',
    tier: 'should',
    neverNag: true,
    safety: 'A break, not a fix. If you are past tired — not sleeping, dreading every day, or feeling you cannot keep going — talk to your GP this week rather than waiting for the calendar to help. Carer support lines exist for exactly this.',
  },
  {
    id: 'carer-ask-for-cover',
    evidenceLevel: 'D',
    title: 'Ask for cover, once a week',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family', 'personal'],
    summary: 'Ten minutes on Sunday: name one thing someone else could carry this week, and ask them.',
    why: 'Practical help and someone to lean on are what soften the road from a heavy week to burning out, across the carer research. The asking is the step carers skip, so this makes it a fixed ten minutes rather than a thing you would do if it got bad enough.',
    attribution: ['Jordan Peterson'],
    days: [0],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '18:00', windowMin: 120 },
    energy: 'evening',
    tier: 'should',
    neverNag: true,
    safety: 'One ask, small enough to say yes to. If there is genuinely nobody to ask, that is what carer organisations and your GP are for — say so to them.',
  },
  {
    id: 'carer-ten-minutes',
    evidenceLevel: 'D',
    title: 'Ten minutes that are not caring',
    pillar: 'connection',
    area: 'health',
    goalDomains: ['family', 'health', 'personal'],
    summary: 'Ten minutes in the middle of the day that belong to nobody else — a walk to the corner, a coffee sat down, the door shut.',
    why: 'Short breaks inside a long day of caring do not have trials of their own; the case for them is borrowed from the shift-work and burnout research, where a small pause before the hardest stretch changes how the rest of the day goes. Cheap, and worth testing on yourself.',
    attribution: ['Andrew Huberman'],
    days: [1, 2, 3, 4, 5],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '13:00', windowMin: 180 },
    energy: 'midday',
    tier: 'should',
    neverNag: true,
    safety: 'Not a reason to leave anyone unsafe. Ten minutes in the next room counts.',
  },

  // ── Connection: teenagers ────────────────────────────────────────────
  {
    id: 'teen-side-by-side',
    evidenceLevel: 'D',
    title: 'The drive, the dog, the dishes',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family'],
    summary: 'Half an hour side by side with a teenager, doing something — the drive, the dog, the washing up — with no questions lined up.',
    why: 'Teenagers say more sideways than face to face, and the big time-use study found that engaged family time in the teenage years, not the total hours, went with fewer risky choices. Nobody has trialled the car as a setting; what is tested is that the time has to be theirs to fill, not an interview.',
    attribution: ['Jordan Peterson'],
    days: [2, 5],
    durationMin: 30,
    anchor: { kind: 'fixed', start: '17:00', windowMin: 180 },
    energy: 'evening',
    tier: 'should',
    safety: 'If they do not want to talk, that is allowed. The point is being there when they do. A teenager who has gone quiet for weeks, stopped eating or sleeping, or dropped every friend is a conversation with your GP or the school, not a longer drive.',
  },
  {
    id: 'teen-their-call',
    evidenceLevel: 'C',
    title: 'One decision that is theirs',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family', 'behaviour'],
    summary: 'Once a week, hand a teenager one real decision — the meal, the plan, the route, the rule — and back it.',
    why: 'Across dozens of studies, teenagers whose parents give them real say do better on mood and motivation than those who are steered, and diary work finds a single moment of being trusted lifts the same day. The effect varies a lot between families, which is why it is one decision a week and not a new regime.',
    attribution: ['Jordan Peterson'],
    days: [0],
    durationMin: 15,
    anchor: { kind: 'fixed', start: '18:30', windowMin: 120 },
    energy: 'evening',
    tier: 'should',
    safety: 'A real decision with a real yes at the end, not a test they can fail. Safety calls stay yours, and saying so plainly is part of it.',
  },

  // ── Connection: couples ──────────────────────────────────────────────
  {
    id: 'turning-toward',
    evidenceLevel: 'D',
    title: 'Answer the small things',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship'],
    summary: 'When they show you something, say something, sigh — look up and answer it. Most days, for a week at a time.',
    why: 'In the best-known couples lab, the people still together years later had answered each other’s small openings most of the time; the ones who split had mostly not. That was watched, not tested, and the famous prediction numbers did not hold up on fresh couples — so take it as the cheapest habit here, not a law.',
    attribution: ['John Gottman', 'Julie Gottman'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 5,
    anchor: { kind: 'fixed', start: '19:30', windowMin: 120 },
    energy: 'evening',
    tier: 'could',
  },
  {
    id: 'conflict-reappraisal-write',
    evidenceLevel: 'C',
    title: 'The last argument, as a stranger would see it',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship', 'behaviour'],
    summary: 'Ten written minutes: the last disagreement described the way a fair outsider who wanted the best for you both would describe it.',
    why: 'One two-year trial gave half its couples three seven-minute writing exercises like this; the usual slide in how they felt about the marriage stopped in that half and carried on in the other. One study, one site, so a good bet rather than a settled fact — and it is the only version of "repair" here that has been tested.',
    attribution: ['Eli Finkel'],
    days: [0],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '20:30', windowMin: 90 },
    energy: 'evening',
    tier: 'could',
    sessionType: 'journal',
    safety: 'About your own view of a disagreement, never a case against your partner. Out of scope where there is fear or anything you would call abuse — that needs a professional, and support lines exist for exactly this.',
  },
  {
    id: 'partner-novelty',
    evidenceLevel: 'C',
    title: 'Something neither of you has done',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship', 'experience'],
    summary: 'Once a week, ninety minutes on something new to both of you — a route, a class, a place, a game — rather than the usual dinner.',
    why: 'Small experiments that sent couples to do something new and a bit demanding together found them closer afterwards than couples given something pleasant and familiar, and surveys find the same link. Small samples, so a modest effect held loosely.',
    attribution: ['Arthur Aron', 'Tim Ferriss'],
    days: [6],
    durationMin: 90,
    anchor: { kind: 'fixed', start: '14:00', windowMin: 240 },
    energy: 'any',
    tier: 'could',
    safety: 'New, not extreme. The point is doing it together, not the thing itself.',
  },

  // ── Connection: grown-up children ────────────────────────────────────
  {
    id: 'adult-child-standing-call',
    evidenceLevel: 'D',
    title: 'The standing call',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family'],
    summary: 'The same half hour every week for a call with a grown-up child who has moved out — theirs to cancel, yours to keep.',
    why: 'Nobody has trialled a weekly call. What is known is that contact between parents and grown-up children runs on habit rather than intention, and that closeness in later life tracks how regular the contact was, not how long each visit lasted.',
    attribution: ['Jordan Peterson'],
    days: [0],
    durationMin: 30,
    anchor: { kind: 'fixed', start: '17:00', windowMin: 180 },
    energy: 'evening',
    tier: 'should',
    neverNag: true,
    safety: 'A standing offer, not a standing demand. If they cancel three weeks running, ask what time would suit them rather than holding the slot against them.',
  },
];
