/**
 * The knowledge base — evidence-informed practices, structured for planning.
 *
 * Each protocol is a practice distilled *in INTENT's own words* from the
 * public, evidence-based teaching of well-known communicators (Tim Ferriss,
 * Andrew Huberman, Peter Attia, Rhonda Patrick, Jordan Peterson, David
 * Sinclair) and the research they discuss. No transcript text is
 * reproduced; `attribution` credits whose public work popularised the
 * practice and implies no endorsement of INTENT. Sourcing policy:
 * docs/KNOWLEDGE.md.
 *
 * Protocols are machine-plannable: `toRoutine` turns one into a Routine
 * the scheduling engine places automatically, wake/sleep-anchored where it
 * matters. The goal wizard, interview and AI agents draw on the same list,
 * so every pathway in the app is enriched by one shared, reviewable base.
 *
 * All of it is educational structure — never medical advice.
 */

import { newId, toHHMM, toMinutes } from '@/lib/dates';
import type {
  GoalDomain,
  LifeArea,
  LifeProfile,
  PlanTier,
  Routine,
  SessionType,
  Weekday,
} from '@/types/domain';

export type Pillar =
  | 'sleep'
  | 'training'
  | 'nutrition'
  | 'longevity'
  | 'mind'
  | 'wealth'
  | 'leadership'
  | 'connection';

export const PILLAR_LABELS: Record<Pillar, string> = {
  sleep: 'Sleep & energy',
  training: 'Training',
  nutrition: 'Nutrition',
  longevity: 'Longevity',
  mind: 'Mind',
  wealth: 'Wealth',
  leadership: 'Leadership & work',
  connection: 'Connection',
};

/** Where in the day a protocol wants to live. */
interface Anchor {
  /** 'wake'/'sleep' offset in minutes, or a fixed start. */
  kind: 'wake' | 'sleep' | 'fixed';
  offsetMin?: number;
  start?: string;
  /** Latest acceptable start, minutes after preferred. */
  windowMin: number;
  /**
   * A deadline, not an activity — "last coffee by", "kitchen closed".
   * The scheduler may bring these earlier but must never push them later:
   * a cutoff moved to make room has become false, not merely inconvenient.
   * Deadlines are placed rigidly and surface as unplaced rather than drift.
   */
  deadline?: boolean;
}

/**
 * Evidence quality — not all protocols are equally certain, and INTENT
 * says so. Expert communicators are discovery sources; the level grades
 * the underlying research, not the fame of the messenger.
 */
export type EvidenceLevel = 'A' | 'B' | 'C' | 'D' | 'E';

export const EVIDENCE_LABELS: Record<EvidenceLevel, string> = {
  A: 'Strong — meta-analyses / broad consensus',
  B: 'Good — multiple controlled studies',
  C: 'Moderate — observational evidence',
  D: 'Emerging — expert practice',
  E: 'Experimental — a heuristic worth testing on yourself',
};

export interface Protocol {
  id: string;
  evidenceLevel: EvidenceLevel;
  title: string;
  pillar: Pillar;
  area: LifeArea;
  /** Goal domains this practice serves — the goal wizard reads this. */
  goalDomains: GoalDomain[];
  /** What to do, one plain sentence. */
  summary: string;
  /** Why it works — the evidence story, in plain words, no overclaiming. */
  why: string;
  /** Whose public teaching popularised it. Credit, not endorsement. */
  attribution: string[];
  days: Weekday[];
  durationMin: number;
  anchor: Anchor;
  energy: Routine['energy'];
  tier: PlanTier;
  sessionType?: SessionType;
  duringWork?: boolean;
  /** Plain-words caution. Health protocols must have one. */
  safety?: string;
}

export const PROTOCOLS: Protocol[] = [
  // ── Sleep & energy ────────────────────────────────────────────────────
  {
    id: 'morning-light',
    evidenceLevel: 'B',
    title: 'Morning light',
    pillar: 'sleep',
    area: 'health',
    goalDomains: ['health'],
    summary: 'Ten minutes of outdoor light within an hour of waking.',
    why: 'Bright morning light anchors the circadian clock — the single cheapest lever for falling asleep easier at night and feeling alert earlier in the day.',
    attribution: ['Andrew Huberman', 'Rhonda Patrick'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 10,
    anchor: { kind: 'wake', offsetMin: 20, windowMin: 45 },
    energy: 'morning',
    tier: 'could',
    safety: 'Never look at the sun directly; through-window light counts for less but still counts.',
  },
  {
    id: 'wind-down',
    evidenceLevel: 'B',
    title: 'Wind-down breathing',
    pillar: 'sleep',
    area: 'health',
    goalDomains: ['health', 'behaviour'],
    summary: 'A short screens-away wind-down with slow breathing before bed.',
    why: 'Long, slow exhales shift the nervous system toward rest; a consistent pre-sleep routine is one of the most reliable sleep-quality improvements there is.',
    attribution: ['Andrew Huberman', 'Tim Ferriss'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 20,
    anchor: { kind: 'sleep', offsetMin: 35, windowMin: 15 },
    energy: 'evening',
    tier: 'could',
    sessionType: 'breathe',
    safety: 'A steadying tool, not treatment for a sleep disorder.',
  },

  // ── Training ──────────────────────────────────────────────────────────
  {
    id: 'strength',
    evidenceLevel: 'A',
    title: 'Strength training',
    pillar: 'training',
    area: 'health',
    goalDomains: ['fitness', 'health'],
    summary: 'Resistance training most days you can manage — compound lifts first.',
    why: 'Muscle mass and strength are among the strongest known predictors of healthy later life; strength work is the closest thing to a retirement account for the body.',
    attribution: ['Peter Attia', 'Andrew Huberman'],
    days: [1, 3, 5],
    durationMin: 45,
    anchor: { kind: 'fixed', start: '12:05', windowMin: 70 },
    energy: 'any',
    tier: 'should',
    sessionType: 'workout',
    safety: 'Conservative loading, full range you control. No pushing through joint pain.',
  },
  {
    id: 'zone2',
    evidenceLevel: 'B',
    title: 'Zone 2 cardio',
    pillar: 'training',
    area: 'health',
    goalDomains: ['fitness', 'health'],
    summary: 'Steady "can still hold a conversation" cardio — brisk walk, easy ride, easy jog.',
    why: 'Easy aerobic volume builds the mitochondrial base tied to metabolic health and endurance — the biggest return per unmiserable minute for most people.',
    attribution: ['Peter Attia', 'Rhonda Patrick'],
    days: [2, 6],
    durationMin: 40,
    anchor: { kind: 'fixed', start: '17:45', windowMin: 90 },
    energy: 'any',
    tier: 'could',
    safety: 'If you can only gasp out words, ease off — conversational pace is the point.',
  },
  {
    id: 'vo2-intervals',
    evidenceLevel: 'B',
    title: 'VO₂ intervals',
    pillar: 'training',
    area: 'health',
    goalDomains: ['fitness'],
    summary: 'Once a week: four rounds of ~4 minutes hard, ~4 minutes easy.',
    why: 'Peak aerobic capacity correlates with long-term health more strongly than almost any other fitness measure, and one weekly interval session moves it.',
    attribution: ['Peter Attia'],
    days: [4],
    durationMin: 35,
    anchor: { kind: 'fixed', start: '17:45', windowMin: 90 },
    energy: 'any',
    tier: 'could',
    safety: 'Build up over weeks; skip when unwell; hard means hard for you, not a number.',
  },
  {
    id: 'daily-walk',
    evidenceLevel: 'A',
    title: 'The daily walk',
    pillar: 'training',
    area: 'health',
    goalDomains: ['health', 'fitness'],
    summary: 'A brisk 30–40 minute walk, most days — the most underrated training there is.',
    why: 'Walking is Zone 2 in disguise: it builds the same aerobic base, costs no willpower, and is the physical activity people actually sustain for decades.',
    attribution: ['Peter Attia', 'Andrew Huberman'],
    days: [1, 2, 3, 4, 5, 6],
    durationMin: 35,
    anchor: { kind: 'fixed', start: '17:45', windowMin: 90 },
    energy: 'any',
    tier: 'should',
    safety: 'Brisk means you can talk but you notice the pace. Weather is not a reason; clothing is a solution.',
  },
  {
    id: 'post-meal-walk',
    evidenceLevel: 'B',
    title: 'Post-meal walk',
    pillar: 'nutrition',
    area: 'health',
    goalDomains: ['health', 'fitness'],
    summary: 'A ten-to-fifteen-minute walk after the day’s biggest meal.',
    why: 'Light movement after eating blunts the glucose spike a meal produces — a tiny habit with an outsized metabolic effect.',
    attribution: ['Rhonda Patrick', 'Peter Attia'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 15,
    anchor: { kind: 'fixed', start: '18:50', windowMin: 40 },
    energy: 'evening',
    tier: 'could',
  },

  {
    id: 'mobility-10',
    evidenceLevel: 'D',
    title: 'Ten-minute mobility',
    pillar: 'training',
    area: 'health',
    goalDomains: ['fitness', 'health'],
    summary: 'Ten minutes of hips, ankles and shoulders, twice a week.',
    why: 'Stability and range are what let every other kind of training continue into later decades — the piece that decides whether you can still get off the floor at 80.',
    attribution: ['Peter Attia'],
    days: [2, 6],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '07:15', windowMin: 60 },
    energy: 'morning',
    tier: 'could',
    safety: 'Range you control, never bounced into. Discomfort fine, pain no.',
  },
  {
    id: 'cold-finish',
    evidenceLevel: 'C',
    title: 'Cold-shower finish',
    pillar: 'training',
    area: 'health',
    goalDomains: ['health', 'behaviour'],
    summary: 'End the morning shower with 30–60 seconds cold.',
    why: 'Brief deliberate cold reliably spikes alertness and mood chemistry for hours — and practising the first uncomfortable minute is rehearsal for every urge you’ll surf later.',
    attribution: ['Andrew Huberman', 'Rhonda Patrick'],
    days: [1, 2, 3, 4, 5],
    durationMin: 5,
    anchor: { kind: 'wake', offsetMin: 35, windowMin: 45 },
    energy: 'morning',
    tier: 'could',
    safety: 'Uncomfortable, never painful. Heart conditions → clinician first. Never combine cold water with open water alone.',
  },

  // ── Nutrition ─────────────────────────────────────────────────────────
  {
    id: 'protein-breakfast',
    evidenceLevel: 'B',
    title: 'Protein-first breakfast',
    pillar: 'nutrition',
    area: 'health',
    goalDomains: ['health', 'fitness'],
    summary: 'Roughly 30 g of protein within a couple of hours of waking.',
    why: 'A protein-anchored first meal steadies appetite and energy for the whole day and front-loads the daily protein target where it’s easiest to hit.',
    attribution: ['Rhonda Patrick', 'Peter Attia'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 15,
    anchor: { kind: 'wake', offsetMin: 60, windowMin: 75 },
    energy: 'morning',
    tier: 'could',
  },
  {
    id: 'caffeine-cutoff',
    evidenceLevel: 'B',
    title: 'Caffeine cutoff',
    pillar: 'sleep',
    area: 'health',
    goalDomains: ['health'],
    summary: 'Last caffeine of the day, ten hours before your bedtime.',
    why: 'Caffeine’s half-life is 5–6 hours: a quarter of that afternoon coffee is still circulating at midnight, quietly shaving deep sleep you never see. Ten hours leaves only a trace by lights-out.',
    attribution: ['Andrew Huberman', 'Peter Attia'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 5,
    // Anchored to BEDTIME, like every other sleep-protective protocol, and
    // marked a deadline so the placement pass can never move it later.
    anchor: { kind: 'sleep', offsetMin: 10 * 60, windowMin: 30, deadline: true },
    energy: 'midday',
    tier: 'could',
  },
  {
    id: 'meal-sketch',
    evidenceLevel: 'B',
    title: 'Weekly meal sketch',
    pillar: 'nutrition',
    area: 'health',
    goalDomains: ['health', 'fitness'],
    summary: 'Fifteen Sunday minutes deciding the week’s dinners — protein first, mostly whole foods.',
    why: 'Deciding once removes seven days of willpower decisions. Anchoring each meal on protein (~1.6–2.2 g/kg/day across the day) protects muscle and keeps you full.',
    attribution: ['Peter Attia', 'Rhonda Patrick', 'Tim Ferriss'],
    days: [0],
    durationMin: 15,
    anchor: { kind: 'fixed', start: '16:00', windowMin: 60 },
    energy: 'any',
    tier: 'could',
    sessionType: 'meal_plan',
  },
  {
    id: 'kitchen-closed',
    evidenceLevel: 'C',
    title: 'Kitchen closes',
    pillar: 'nutrition',
    area: 'health',
    goalDomains: ['health'],
    summary: 'A consistent last bite by three hours before bed; eat within a daylight window.',
    why: 'A steady, earlier eating window supports sleep and metabolic rhythm; late eating works against both.',
    attribution: ['David Sinclair', 'Rhonda Patrick'],
    days: [0, 1, 2, 3, 4],
    durationMin: 5,
    // Also a deadline — "last bite by", not an activity to slot in.
    anchor: { kind: 'sleep', offsetMin: 180, windowMin: 30, deadline: true },
    energy: 'evening',
    tier: 'could',
    safety: 'Structure, not restriction — skip this protocol entirely if eating windows are a fraught topic for you.',
  },

  {
    id: 'fasting-window',
    evidenceLevel: 'C',
    title: 'Hold the eating window',
    pillar: 'nutrition',
    area: 'health',
    goalDomains: ['health'],
    summary: 'A consistent daily eating window — first bite and last bite at roughly the same times.',
    why: 'Consistency beats duration: a steady window supports metabolic rhythm and quietly caps grazing, without counting anything.',
    attribution: ['Peter Attia', 'David Sinclair', 'Rhonda Patrick'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 5,
    anchor: { kind: 'sleep', offsetMin: 180, windowMin: 30 },
    energy: 'evening',
    tier: 'could',
    safety:
      'Not for everyone — skip entirely if pregnant, underweight, or if restriction has ever been a fraught topic. Protein and training quality come first.',
  },

  // ── Longevity ─────────────────────────────────────────────────────────
  {
    id: 'sauna',
    evidenceLevel: 'C',
    title: 'Sauna sessions',
    pillar: 'longevity',
    area: 'health',
    goalDomains: ['health'],
    summary: 'Two to four sauna sessions a week, ~15–20 minutes at a heat you tolerate well.',
    why: 'Regular sauna use is associated in long-running Finnish cohort studies with lower cardiovascular risk, and reliably helps relaxation and sleep.',
    attribution: ['Rhonda Patrick', 'David Sinclair'],
    days: [3, 6],
    durationMin: 30,
    anchor: { kind: 'fixed', start: '18:45', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
    safety: 'Hydrate; no alcohol around sessions; heart conditions or pregnancy → talk to a clinician first.',
  },

  // ── Mind ──────────────────────────────────────────────────────────────
  {
    id: 'meditation-10',
    evidenceLevel: 'B',
    title: 'Ten minutes of stillness',
    pillar: 'mind',
    area: 'health',
    goalDomains: ['health', 'personal'],
    summary: 'A short daily sit — breath as the anchor, thoughts allowed to pass.',
    why: 'The single most common daily practice among the high performers Ferriss has interviewed; short consistent sessions measurably improve attention and stress recovery.',
    attribution: ['Tim Ferriss', 'Andrew Huberman'],
    days: [0, 2, 4],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '13:00', windowMin: 45 },
    energy: 'midday',
    tier: 'could',
    sessionType: 'meditate',
    safety: 'Non-clinical; no therapeutic claims.',
  },
  {
    id: 'nsdr',
    evidenceLevel: 'D',
    title: 'NSDR reset',
    pillar: 'mind',
    area: 'health',
    goalDomains: ['health'],
    summary: 'Ten to twenty minutes of non-sleep deep rest in the afternoon dip.',
    why: 'A guided deep-rest protocol restores alertness and lowers stress without a nap’s grogginess — a legal performance enhancer for the second half of the day.',
    attribution: ['Andrew Huberman'],
    days: [1, 3],
    durationMin: 15,
    anchor: { kind: 'fixed', start: '14:30', windowMin: 60 },
    energy: 'midday',
    tier: 'could',
    sessionType: 'meditate',
  },
  {
    id: 'evening-journal',
    evidenceLevel: 'B',
    title: 'Five-minute journal',
    pillar: 'mind',
    area: 'growth',
    goalDomains: ['personal'],
    summary: 'Five written minutes: what went well, what you’re grateful for, one line for tomorrow.',
    why: 'Brief written gratitude and reflection reliably improve mood and sleep quality, and writing forces the clarity that vague rumination never reaches.',
    attribution: ['Tim Ferriss', 'Jordan Peterson', 'Andrew Huberman'],
    days: [0, 1, 2, 3, 4],
    durationMin: 5,
    anchor: { kind: 'sleep', offsetMin: 60, windowMin: 30 },
    energy: 'evening',
    tier: 'could',
    sessionType: 'journal',
  },

  {
    id: 'creative-block',
    evidenceLevel: 'D',
    title: 'Creative block',
    pillar: 'mind',
    area: 'growth',
    goalDomains: ['personal'],
    summary: 'Two protected sessions a week for the creative thing — making, not consuming.',
    why: 'Creative practice is the most common thread among people who describe their weeks as good ones — and it only happens when it has a defended place on the calendar.',
    attribution: ['Tim Ferriss', 'Jordan Peterson'],
    days: [2, 6],
    durationMin: 45,
    anchor: { kind: 'fixed', start: '19:45', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
  },

  // ── Wealth ────────────────────────────────────────────────────────────
  {
    id: 'money-checkin',
    evidenceLevel: 'D',
    title: 'Weekly money check-in',
    pillar: 'wealth',
    area: 'admin',
    goalDomains: ['finance'],
    summary: 'Thirty Sunday minutes: automate the transfer first, then review the week’s money.',
    why: 'Automation beats willpower budgeting — pay the goal first and the review becomes observation, not judgement. A weekly cadence catches drift while it’s still small.',
    attribution: ['Tim Ferriss'],
    days: [0],
    durationMin: 30,
    anchor: { kind: 'fixed', start: '19:30', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
  },
  {
    id: 'fear-setting',
    evidenceLevel: 'E',
    title: 'Fear-setting',
    pillar: 'wealth',
    area: 'growth',
    goalDomains: ['business', 'career', 'personal', 'finance'],
    summary: 'Define the decision you’re avoiding: worst case, how you’d prevent it, how you’d repair it.',
    why: 'Stalled decisions are usually unexamined fears. Writing the worst case down shrinks it to actual size — the exercise Ferriss credits for his biggest moves. Monthly is plenty.',
    attribution: ['Tim Ferriss'],
    days: [6],
    durationMin: 30,
    anchor: { kind: 'fixed', start: '09:30', windowMin: 120 },
    energy: 'morning',
    tier: 'could',
  },

  // ── Leadership & work ─────────────────────────────────────────────────
  {
    id: 'deep-work',
    evidenceLevel: 'D',
    title: 'Deep work block',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career'],
    summary: 'A protected 60–90 minute single-task block before the day fragments.',
    why: 'The highest-leverage work is the kind interruptions kill. One protected morning block routinely outproduces a scattered afternoon.',
    attribution: ['Tim Ferriss'],
    days: [1, 2],
    durationMin: 60,
    anchor: { kind: 'fixed', start: '09:15', windowMin: 60 },
    energy: 'morning',
    tier: 'must',
    duringWork: true,
  },
  {
    id: 'weekly-business-review',
    evidenceLevel: 'D',
    title: 'Weekly business review',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career'],
    summary: 'A weekly structured review: what moved, what stalled, the one lever for next week.',
    why: 'Aim, articulate, adjust: writing down what you’re actually aiming at — and confronting what happened — is the core discipline both Peterson and Ferriss teach for any serious goal.',
    attribution: ['Jordan Peterson', 'Tim Ferriss'],
    days: [1],
    durationMin: 90,
    anchor: { kind: 'fixed', start: '09:15', windowMin: 60 },
    energy: 'morning',
    tier: 'must',
    duringWork: true,
    sessionType: 'business_review',
  },
  {
    id: 'eighty-twenty-audit',
    evidenceLevel: 'E',
    title: '80/20 audit',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career'],
    summary: 'Roughly monthly: name the 20% producing most of the results — and the 20% producing most of the drag.',
    why: 'A small share of activities produces most of the outcome; naming and cutting the drag is where leverage actually comes from.',
    attribution: ['Tim Ferriss'],
    days: [5],
    durationMin: 45,
    anchor: { kind: 'fixed', start: '14:00', windowMin: 90 },
    energy: 'midday',
    tier: 'could',
    duringWork: true,
  },

  {
    id: 'week-preview',
    evidenceLevel: 'E',
    title: 'Sunday week preview',
    pillar: 'leadership',
    area: 'growth',
    goalDomains: ['personal', 'business', 'career'],
    summary: 'Fifteen Sunday-evening minutes looking at the week ahead: the three things that matter, the one conflict to defuse now.',
    why: 'The Sunday reset — meals decided, money checked, week previewed — is the ritual stack that makes Monday start already-won instead of already-behind.',
    attribution: ['Tim Ferriss', 'Jordan Peterson'],
    days: [0],
    durationMin: 15,
    anchor: { kind: 'fixed', start: '20:15', windowMin: 45 },
    energy: 'evening',
    tier: 'could',
  },

  // ── Connection ────────────────────────────────────────────────────────
  {
    id: 'friend-reach-out',
    evidenceLevel: 'C',
    title: 'Reach out, make a plan',
    pillar: 'connection',
    area: 'enjoyment',
    goalDomains: ['friends'],
    summary: 'One message a week that turns into a concrete plan with someone you like.',
    why: 'Strong relationships are the most consistent predictor of long-term wellbeing in the research — and they run on logistics, not sentiment.',
    attribution: ['Jordan Peterson'],
    days: [3],
    durationMin: 15,
    anchor: { kind: 'fixed', start: '12:45', windowMin: 30 },
    energy: 'midday',
    tier: 'could',
  },

  // ── Connection: partner ───────────────────────────────────────────────
  {
    id: 'partner-reunion',
    evidenceLevel: 'D',
    title: 'The first five minutes',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship', 'family'],
    summary: 'The first five minutes back together get your attention before anything else does.',
    why: 'Work stress reliably follows people home as withdrawal; daily-diary research finds the reunion sets the tone for the whole evening, which makes five deliberate minutes the cheapest place to spend attention.',
    attribution: ['John Gottman', 'Julie Gottman'],
    days: [1, 2, 3, 4, 5],
    durationMin: 5,
    anchor: { kind: 'fixed', start: '17:35', windowMin: 90 },
    energy: 'evening',
    tier: 'should',
  },
  {
    id: 'partner-appreciation',
    evidenceLevel: 'C',
    title: 'Name one thing',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship', 'behaviour'],
    summary: 'Say one specific thing you noticed and valued about them — out loud, most days.',
    why: 'Happy couples run a lopsided ratio of warm to sour moments. Diary studies and small experiments link specific, spoken appreciation to feeling valued — and to raising hard things more easily.',
    attribution: ['John Gottman', 'Robert Emmons'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 5,
    anchor: { kind: 'sleep', offsetMin: 150, windowMin: 90 },
    energy: 'evening',
    tier: 'should',
  },
  {
    id: 'partner-checkin-weekly',
    evidenceLevel: 'E',
    title: 'Weekly two-of-you check-in',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship', 'family'],
    summary: 'Twenty minutes on Sunday: the week ahead, who carries what, one thing each of you needs.',
    why: 'How fairly the load feels shared tracks closely with satisfaction in survey after survey. The meeting itself is untested — a heuristic for making the invisible load visible before it becomes an argument.',
    attribution: ['Jordan Peterson', 'Tim Ferriss'],
    days: [0],
    durationMin: 20,
    anchor: { kind: 'fixed', start: '21:00', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
    safety: 'A logistics conversation, not a grievance hearing. If the same subject keeps ending badly, that is a sign to talk to a couples therapist — not to hold more meetings.',
  },
  {
    id: 'state-of-us',
    evidenceLevel: 'C',
    title: 'State of us',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship', 'personal'],
    summary: 'Roughly monthly, forty-five unhurried minutes on the relationship itself, not the logistics.',
    why: 'The few randomised trials here found brief structured reflection — minutes a year, not hours a week — slowed the ordinary decline in satisfaction about as well as full skills courses did.',
    attribution: ['John Gottman', 'Julie Gottman'],
    days: [6],
    durationMin: 45,
    anchor: { kind: 'fixed', start: '10:00', windowMin: 180 },
    energy: 'morning',
    tier: 'could',
    safety: 'Educational structure, not couples therapy. If this conversation reliably turns into the same fight, or either of you dreads it, a couples therapist is the right next step.',
  },
  {
    id: 'repair-rehearsal',
    evidenceLevel: 'D',
    title: 'Repair, rehearsed',
    pillar: 'connection',
    area: 'relationship',
    goalDomains: ['relationship', 'behaviour'],
    summary: 'Ten written minutes on the last friction: what set it off, and the words that would have cooled it.',
    why: 'Stable couples are not the ones who avoid conflict, they are the ones who de-escalate early. The repair itself happens in the moment; what you can practise beforehand is the phrase you reach for.',
    attribution: ['John Gottman'],
    days: [4],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '20:45', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
    sessionType: 'journal',
    safety: 'Private reflection on your own part, never a case file on your partner. Out of scope entirely where there is fear, coercion or anything you would call abuse — that needs a professional, and support lines exist for exactly this.',
  },

  // ── Connection: family time & adventure ───────────────────────────────
  {
    id: 'family-adventure',
    evidenceLevel: 'C',
    title: 'The booked-in family adventure',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family', 'experience'],
    summary: 'One family outing a week, chosen and in the calendar before the week starts.',
    why: 'Experiences tend to buy more lasting happiness than possessions, and the calendar entry is what turns the intention into an actual Saturday. Effect sizes are modest and debated.',
    attribution: ['Thomas Gilovich', 'Tim Ferriss'],
    days: [6],
    durationMin: 180,
    anchor: { kind: 'fixed', start: '09:30', windowMin: 120 },
    energy: 'morning',
    tier: 'should',
    safety: 'Match the outing to the youngest child’s stamina — an adventure nobody enjoyed is worse than a slow morning at home.',
  },
  {
    id: 'one-on-one-child',
    evidenceLevel: 'D',
    title: 'One-on-one with each child',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family'],
    summary: 'Twenty-odd minutes a week with each child, one at a time, doing what they choose.',
    why: 'Child-led one-to-one time is a building block of parenting programmes that have been trialled properly, though it has rarely been tested on its own.',
    attribution: ['Jordan Peterson'],
    days: [2, 4],
    durationMin: 25,
    anchor: { kind: 'fixed', start: '17:15', windowMin: 60 },
    energy: 'evening',
    tier: 'should',
    safety: 'Let the child pick and lead. If it starts feeling like an appointment they have to perform at, make it shorter or let it go.',
  },
  {
    id: 'trip-anticipation',
    evidenceLevel: 'D',
    title: 'Stretch the anticipation',
    pillar: 'connection',
    area: 'enjoyment',
    goalDomains: ['experience', 'family'],
    summary: 'Fifteen minutes a week on the next trip: one decision made, one detail shared with everyone going.',
    why: 'Holidaymakers report more happiness before a trip than after it, so booking early may be where much of the benefit lives — an observational finding we extend on purpose.',
    attribution: ['Jeroen Nawijn', 'Thomas Gilovich'],
    days: [4],
    durationMin: 15,
    anchor: { kind: 'fixed', start: '20:00', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
    safety: 'Keep plans loose enough to change. Building a trip up as the thing that will fix a hard year sets everyone up to be let down.',
  },
  {
    id: 'device-free-meal',
    evidenceLevel: 'C',
    title: 'The device-free family meal',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family'],
    summary: 'A shared evening meal on set nights, with every phone out of the room.',
    why: 'Frequent shared meals are associated with better diet and psychosocial outcomes in children across many studies — all observational, and such families differ in other ways too.',
    attribution: ['Barbara Fiese'],
    days: [0, 1, 2, 3, 4],
    durationMin: 40,
    anchor: { kind: 'fixed', start: '18:15', windowMin: 45 },
    energy: 'evening',
    tier: 'should',
    safety: 'Aim only at the nights that are realistic. Conversation, not inspection — a meal that becomes a performance review stops being the good thing here.',
  },
  {
    id: 'family-memory-review',
    evidenceLevel: 'D',
    title: 'Look back at it together',
    pillar: 'connection',
    area: 'enjoyment',
    goalDomains: ['family', 'experience', 'personal'],
    summary: 'Ten Sunday minutes going through the week’s photos, out loud, together.',
    why: 'Savouring a good moment on purpose has small experimental support for lifting mood, and it stretches an experience past the day it happened. The studies are small and short.',
    attribution: ['Fred Bryant', 'Tim Ferriss'],
    days: [0],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '17:00', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
    safety: 'Follow what the child wants to talk about, and skip anything anyone found upsetting. Educational structure, never a wellbeing intervention.',
  },
  {
    id: 'family-ritual-anchor',
    evidenceLevel: 'C',
    title: 'One unmoveable family ritual',
    pillar: 'connection',
    area: 'family',
    goalDomains: ['family'],
    summary: 'One small thing that happens at the same time every week, whoever else is busy.',
    why: 'Predictable family routines are associated with steadier child wellbeing across decades of research — most of it correlational, so the arrow’s direction is unsettled.',
    attribution: ['Barbara Fiese', 'Jordan Peterson'],
    days: [5],
    durationMin: 90,
    anchor: { kind: 'fixed', start: '18:30', windowMin: 60 },
    energy: 'evening',
    tier: 'should',
    safety: 'Small and repeatable beats big and abandoned. If it turns into an obligation everyone dreads, change the ritual rather than defend it.',
  },

  // ── Wealth: the money system ──────────────────────────────────────────
  {
    id: 'payday-automation',
    evidenceLevel: 'A',
    title: 'Payday transfer, set once',
    pillar: 'wealth',
    area: 'admin',
    goalDomains: ['finance', 'behaviour'],
    summary: 'Set the payday transfer so the saving leaves automatically, before any of it can be spent.',
    why: 'Large workplace field trials found that making saving the default moves how much people keep far more than intention or budgeting does. The transfer is the intervention — you decide once.',
    attribution: ['Richard Thaler', 'Shlomo Benartzi', 'Tim Ferriss'],
    days: [5],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '18:00', windowMin: 120 },
    energy: 'evening',
    tier: 'should',
    safety: 'Where the money lands — account type, product, tax treatment — is a licensed adviser or accountant question. INTENT helps you build the habit of the transfer, nothing more. Education, never financial advice.',
  },
  {
    id: 'raise-precommit',
    evidenceLevel: 'B',
    title: 'Spend the raise before it arrives',
    pillar: 'wealth',
    area: 'admin',
    goalDomains: ['finance', 'personal', 'behaviour'],
    summary: 'Once a quarter, write down what share of the next pay rise or bonus goes straight to the transfer.',
    why: 'Committing income you do not hold yet avoids the sting of giving up money you do — the mechanism behind the best-known escalating-saving programme. A pay rise is when lifestyle quietly expands.',
    attribution: ['Richard Thaler', 'Shlomo Benartzi'],
    days: [6],
    durationMin: 20,
    anchor: { kind: 'fixed', start: '11:00', windowMin: 120 },
    energy: 'morning',
    tier: 'could',
    safety: 'Choosing a share is a habit, not an allocation plan — pension, tax and investment choices belong with a licensed adviser. Education, never financial advice.',
  },
  {
    id: 'subscription-audit',
    evidenceLevel: 'C',
    title: 'Recurring-charge audit',
    pillar: 'wealth',
    area: 'admin',
    goalDomains: ['finance', 'business'],
    summary: 'Once a quarter, list every recurring charge and cancel what you would not sign up for again today.',
    why: 'Card and billing data show recurring payments run on for years on inattention alone — people cancel when something finally forces them to look. The audit is that forcing function.',
    attribution: ['Tim Ferriss'],
    days: [2],
    durationMin: 25,
    anchor: { kind: 'fixed', start: '20:00', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
    safety: 'Check what a cancellation actually ends before you cancel it — insurance, indemnity and health cover can be far harder to restart than to stop.',
  },
  {
    id: 'debt-order-review',
    evidenceLevel: 'C',
    title: 'Pick a debt order you will finish',
    pillar: 'wealth',
    area: 'admin',
    goalDomains: ['finance', 'behaviour'],
    summary: 'Monthly: list every balance with its rate, choose one order, and automate the extra payment against the first one only.',
    why: 'Highest rate first costs least on paper; the follow-through evidence is mixed and leans to smallest balance first, since closing an account is visible progress. Finishing matters more than the order.',
    attribution: ['Richard Thaler'],
    days: [1],
    durationMin: 20,
    anchor: { kind: 'fixed', start: '19:00', windowMin: 60 },
    energy: 'evening',
    tier: 'could',
    safety: 'If payments are already being missed, or a lender is chasing, that is a licensed debt adviser or a nonprofit debt charity — not a habit app. Education, never financial advice.',
  },
  {
    id: 'purchase-delay',
    evidenceLevel: 'E',
    title: 'Sleep on it, then decide',
    pillar: 'wealth',
    area: 'admin',
    goalDomains: ['finance', 'behaviour', 'personal'],
    summary: 'Optional spending over a threshold you set waits 72 hours on a list; twice a week, buy only what still earns it.',
    why: 'Wanting is loudest in the moment and fades on its own, so the delay hands the call to the calm version of you. Present bias is well evidenced; the rule itself is a heuristic to test on yourself.',
    attribution: ['Tim Ferriss'],
    days: [3, 6],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '12:30', windowMin: 90 },
    energy: 'midday',
    tier: 'could',
    safety: 'The delay is for optional spending only — never postpone medical care, repairs that worsen, or anything with a real deadline.',
  },
  {
    id: 'net-worth-check',
    evidenceLevel: 'B',
    title: 'Quarterly position check',
    pillar: 'wealth',
    area: 'admin',
    goalDomains: ['finance', 'personal'],
    summary: 'Once a quarter, write everything owned minus everything owed as one number, in the same place each time.',
    why: 'Meta-analytic work on goal pursuit finds that monitoring progress, and writing it down, makes reaching a goal more likely; the effect is general, not money-specific. Quarterly catches drift without chasing noise.',
    attribution: ['Peter Attia'],
    days: [0],
    durationMin: 20,
    anchor: { kind: 'fixed', start: '10:00', windowMin: 120 },
    energy: 'morning',
    tier: 'could',
    safety: 'A position number is a measurement, not a verdict on what to do next — investment, pension and tax decisions belong with a licensed professional. Education, never financial advice.',
  },

  // ── Leadership: decision quality, delegation, attention ───────────────
  {
    id: 'if-then-plan',
    evidenceLevel: 'A',
    title: 'If-then plan the week',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career', 'personal'],
    summary: 'Ten Monday minutes turning each commitment into “if X, then Y” — including the line that defends the deep block.',
    why: 'Naming the exact when, where and first move — plus one coping line for the obstacle you can already see — is among the best-replicated findings in behaviour-change research: medium-sized effects across roughly a hundred studies, largest for intentions that keep slipping.',
    attribution: ['Peter Gollwitzer', 'Paschal Sheeran'],
    days: [1],
    durationMin: 10,
    anchor: { kind: 'fixed', start: '09:05', windowMin: 60 },
    energy: 'morning',
    tier: 'should',
    duringWork: true,
  },
  {
    id: 'decision-journal',
    evidenceLevel: 'B',
    title: 'Decision journal',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career'],
    summary: 'Twenty Friday minutes: log each consequential call — expectation, confidence, review date — and reread what’s due.',
    why: 'Knowing how it turned out overwrites what you actually believed, so experience alone teaches badly. A written forecast with a confidence number and a booked reread restores the feedback loop that calibration research shows sharpens judgement.',
    attribution: ['Philip Tetlock', 'Annie Duke'],
    days: [5],
    durationMin: 20,
    anchor: { kind: 'fixed', start: '16:00', windowMin: 90 },
    energy: 'any',
    tier: 'should',
    sessionType: 'journal',
    duringWork: true,
    safety: 'Your own calls, not a file on other people — a journal that might be read as a performance record stops being honest.',
  },
  {
    id: 'pre-mortem',
    evidenceLevel: 'C',
    title: 'Pre-mortem before the one-way door',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career'],
    summary: 'Before a commitment that is hard to undo: assume a year has passed and it failed, then write every reason why.',
    why: 'Treating the failure as already certain gets people to generate more concrete reasons than asking what might go wrong — one classic experiment, consistent with wider “consider the opposite” work. Whether it improves real outcomes is untested.',
    attribution: ['Gary Klein', 'Daniel Kahneman'],
    days: [4],
    durationMin: 30,
    anchor: { kind: 'fixed', start: '14:00', windowMin: 120 },
    energy: 'midday',
    tier: 'could',
    duringWork: true,
    safety: 'A thinking tool, not a veto. Run it on the calls that are hard to undo and let reversible ones stay fast.',
  },
  {
    id: 'one-on-one-cadence',
    evidenceLevel: 'C',
    title: 'One-on-one cadence',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career'],
    summary: 'A standing weekly half-hour per direct — their agenda, one blocker question, feedback about the work not the person.',
    why: 'Manager-relationship quality tracks with engagement and retention, but that evidence is mostly observational. The firmer part is narrower: in the classic review, feedback aimed at the person made performance worse about a third of the time.',
    attribution: ['Andrew Grove', 'Kim Scott'],
    days: [2],
    durationMin: 30,
    anchor: { kind: 'fixed', start: '11:00', windowMin: 120 },
    energy: 'any',
    tier: 'should',
    duringWork: true,
    safety: 'Their agenda, not a status report — and nothing here replaces a formal process when the subject is pay, conduct or someone’s job.',
  },
  {
    id: 'delegation-pass',
    evidenceLevel: 'D',
    title: 'Weekly delegation pass',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career'],
    summary: 'Twenty minutes to take one recurring thing off your desk: kill it, automate it, or hand it over with an owner and a date.',
    why: 'People reliably improve things by adding rather than removing — a robust experimental finding — so subtraction needs a booked slot or it never happens. That this particular weekly pass improves a company is practitioner experience.',
    attribution: ['Leidy Klotz', 'Tim Ferriss'],
    days: [3],
    durationMin: 20,
    anchor: { kind: 'fixed', start: '15:30', windowMin: 120 },
    energy: 'midday',
    tier: 'could',
    duringWork: true,
  },
  {
    id: 'think-day',
    evidenceLevel: 'E',
    title: 'Quarterly think day',
    pillar: 'leadership',
    area: 'work',
    goalDomains: ['business', 'career', 'personal'],
    summary: 'Once a quarter, two protected hours with no inputs: the three-year question, then what this quarter has to prove.',
    why: 'Short structured written reflection has improved performance in field experiments, but stretching a fifteen-minute result to a quarterly half-day is extrapolation. A well-liked practice worth testing on yourself, not a settled finding.',
    attribution: ['Tim Ferriss'],
    days: [5],
    durationMin: 120,
    anchor: { kind: 'fixed', start: '09:15', windowMin: 180 },
    energy: 'morning',
    tier: 'could',
    duringWork: true,
    safety: 'Thinking time is not a substitute for talking to customers and the people doing the work.',
  },

  // ── Mind: depth ───────────────────────────────────────────────────────
  {
    id: 'cyclic-sighing',
    evidenceLevel: 'B',
    title: 'Cyclic sighing',
    pillar: 'mind',
    area: 'health',
    goalDomains: ['health', 'behaviour'],
    summary: 'Five minutes of double inhale through the nose, then a long, slow exhale.',
    why: 'In a randomised trial that pitted five daily minutes of breathwork against five minutes of mindfulness meditation, cyclic sighing came out ahead on day-to-day mood and produced the larger drop in resting breathing rate. The long exhale is the working part; the second sip of air simply makes it possible.',
    attribution: ['Andrew Huberman'],
    days: [1, 2, 3, 4, 5],
    durationMin: 5,
    anchor: { kind: 'fixed', start: '15:00', windowMin: 150 },
    energy: 'any',
    tier: 'could',
    sessionType: 'breathe',
    safety: 'A steadying tool, not treatment. Stop if you feel light-headed, and skip it entirely in water or behind the wheel. If you are pregnant or have a heart or breathing condition, check with your doctor before making it a daily habit.',
  },
  {
    id: 'loving-kindness',
    evidenceLevel: 'C',
    title: 'Goodwill practice',
    pillar: 'mind',
    area: 'health',
    goalDomains: ['health', 'personal'],
    summary: 'Five minutes directing plain, specific goodwill — someone easy, then yourself, then someone difficult.',
    why: 'Warmth toward other people behaves like a trainable skill rather than a fixed trait, and short daily practice is associated with modest lifts in positive mood and in how connected people report feeling. The trials are small, short and hard to blind, so treat this as a fortnight’s experiment on yourself rather than a settled result.',
    attribution: ['Tim Ferriss', 'Andrew Huberman'],
    days: [1, 3, 5],
    durationMin: 5,
    anchor: { kind: 'wake', offsetMin: 90, windowMin: 180 },
    energy: 'morning',
    tier: 'could',
    sessionType: 'meditate',
    safety: 'Non-clinical, and not a way to force a feeling. If bringing a difficult person to mind opens more than you expected, stay with the easy one — or leave that step out.',
  },
  {
    id: 'body-scan-sleep',
    evidenceLevel: 'C',
    title: 'Body scan before sleep',
    pillar: 'mind',
    area: 'health',
    goalDomains: ['health', 'behaviour'],
    summary: 'Ten minutes lying down, moving attention slowly from the feet to the head.',
    why: 'A body scan hands the mind a concrete, boring task at exactly the hour it most wants to plan and replay. Relaxation-based wind-downs are associated with modest improvements in how fast people fall asleep and how they rate the night — smaller than the effect of a consistent sleep and wake time, but it stacks on top of one.',
    attribution: ['Andrew Huberman', 'Tim Ferriss'],
    days: [0, 1, 2, 3, 4, 5, 6],
    durationMin: 10,
    anchor: { kind: 'sleep', offsetMin: 15, windowMin: 20 },
    energy: 'evening',
    tier: 'could',
    sessionType: 'meditate',
    safety: 'Falling asleep partway through is fine — that is rather the point here. It is not a fix for insomnia; weeks of bad sleep is a conversation for a doctor or a sleep clinician.',
  },
  {
    id: 'open-monitoring',
    evidenceLevel: 'C',
    title: 'Open-monitoring sit',
    pillar: 'mind',
    area: 'health',
    goalDomains: ['health', 'personal'],
    summary: 'Five minutes noticing whatever shows up — sound, sensation, thought — naming it and letting it go.',
    why: 'Rather than holding one anchor, you practise watching what the mind does. Meta-analyses of mindfulness training find real but modest effects on attention and stress, and open monitoring is the thinner half of that literature — it is rarely tested on its own. Plausible and useful; less certain than the ten-minute breath sit.',
    attribution: ['Tim Ferriss', 'Andrew Huberman'],
    days: [2, 4],
    durationMin: 5,
    anchor: { kind: 'fixed', start: '12:30', windowMin: 120 },
    energy: 'midday',
    tier: 'could',
    sessionType: 'meditate',
    safety: 'Non-clinical. Sitting with whatever arrives suits most people and unsettles some — if a sit leaves you distressed, detached from yourself, or reliably worse than you started, stop the practice and take it to a doctor or a therapist rather than pushing through. Meditation is not a substitute for professional care.',
  },
];

export const protocolById = (id: string): Protocol | undefined =>
  PROTOCOLS.find((p) => p.id === id);

/** Protocols that serve a goal domain, most relevant first. */
export function protocolsForDomain(domain: GoalDomain): Protocol[] {
  return PROTOCOLS.filter((p) => p.goalDomains.includes(domain));
}

function startFor(p: Protocol, profile: LifeProfile | null): string {
  const a = p.anchor;
  if (a.kind === 'wake' && profile) {
    return toHHMM(toMinutes(profile.wakeTime) + (a.offsetMin ?? 0));
  }
  if (a.kind === 'sleep' && profile) {
    return toHHMM((toMinutes(profile.sleepTime) - (a.offsetMin ?? 0) + 1440) % 1440);
  }
  return a.start ?? '12:05';
}

/** A protocol as a schedulable routine, anchored to the user's real day. */
export function toRoutine(p: Protocol, profile: LifeProfile | null, goalId?: string): Routine {
  const start = startFor(p, profile);
  const days =
    profile?.capacity === 'minimal' && p.tier === 'could' && p.days.length > 2
      ? p.days.slice(0, 2)
      : [...p.days];
  return {
    id: newId('r'),
    title: p.title,
    area: p.area,
    goalId,
    protocolId: p.id,
    days,
    durationMin: p.durationMin,
    preferredStart: start,
    preferredEnd: toHHMM((toMinutes(start) + p.anchor.windowMin) % 1440),
    energy: p.energy,
    // A deadline is never flexible: the placement pass may not move it later.
    flexible: !p.duringWork && !p.anchor.deadline,
    protected: false,
    duringWork: p.duringWork,
    sessionType: p.sessionType,
    tier: p.tier,
    active: true,
  };
}

/**
 * Compact grounding for the AI agents: the whole base in a few hundred
 * tokens, so suggestions the model writes stay anchored to the same
 * evidence-based library the deterministic engine plans from.
 */
export function knowledgeContext(): string {
  // Summary + evidence grade only. `why` is the evidence story we show the
  // USER; the planner needs to know what a protocol does and how well
  // supported it is, not to carry our copy in every prompt. Including it
  // made the context grow faster than the library could — this scales.
  return PROTOCOLS.map(
    (p) => `- ${p.title} (${PILLAR_LABELS[p.pillar]}, evidence ${p.evidenceLevel}): ${p.summary}`,
  ).join('\n');
}
